blueprint:
  name: EVSE Charging Control
  description: Automatyzacja regulująca moc ładowania EVSE w zależności od nadwyżki produkcji z fotowoltaiki.
  domain: automation
  input:
    evse_switch:
      name: EVSE Switch
      selector:
        entity:
          domain: switch
    evse_current:
      name: EVSE Configured Current
      selector:
        entity:
          domain: number
    pv_production:
      name: Production PV
      selector:
        entity:
          domain: sensor
    main_consumption:
      name: Main Consumption
      selector:
        entity:
          domain: sensor
    evse_power:
      name: EVSE Power
      selector:
        entity:
          domain: sensor
    battery_soc:
      name: Battery SOC
      selector:
        entity:
          domain: sensor
    battery_power:
      name: Battery Power
      selector:
        entity:
          domain: sensor
    home_consumption:
      name: Home Consumption
      selector:
        entity:
          domain: sensor
    evse_min_run_time_active:
      name: EVSE Minimum Run Time Active
      selector:
        entity:
          domain: input_boolean
    evse_min_run_time:
      name: EVSE Minimum Run Time
      selector:
        entity:
          domain: input_number
    evse_min_run_timer:
      name: EVSE Minimum Run Timer
      selector:
        entity:
          domain: timer

trigger:
  - platform: state
    entity_id: 
      - input: evse_current

condition:
  - condition: template
    value_template: >
      {{ states('sensor.production_pv') | float(0) > (states('sensor.home_consumption') | float(0) + 4.320) }}

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: 
              - input: evse_min_run_time_active
            state: 'off'
        sequence:
          - service: timer.start
            data:
              duration: '00:{{ states("input_number.evse_min_run_time") | int(4) }}:00'
            target:
              entity_id: 
                - input: evse_min_run_timer
          - service: input_boolean.turn_on
            target:
              entity_id: 
                - input: evse_min_run_time_active
      - conditions:
          - condition: template
            value_template: >
              {% set pv_production = states('sensor.production_pv') | float %}
              {% set home_consumption = states('sensor.home_consumption') | float %}
              {% set evse_power = states('sensor.evse_power') | float %}
              {% set battery_power = states('sensor.battery_power') | float %}
              {% set current_evse_current = states('number.evse_configured_current') | float %}
              {% set calculated_power = pv_production - home_consumption %}
              {% set new_evse_current = (calculated_power / 230) | round(1) %}
              {{ new_evse_current >= 6.0 and new_evse_current <= 16.0 and battery_power >= 0 }}
        sequence:
          - service: number.set_value
            data:
              value: >
                {% set pv_production = states('sensor.production_pv') | float %}
                {% set home_consumption = states('sensor.home_consumption') | float %}
                {% set evse_power = states('sensor.evse_power') | float %}
                {% set battery_power = states('sensor.battery_power') | float %}
                {% set current_evse_current = states('number.evse_configured_current') | float %}
                {% set calculated_power = pv_production - home_consumption %}
                {% set new_evse_current = (calculated_power / 230) | round(1) %}
                {{ [new_evse_current, 6.0] | max }}
            target:
              entity_id: 
                - input: evse_current

      - conditions:
          - condition: state
            entity_id: 
              - input: evse_min_run_timer
            state: 'idle'
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: 
                - input: evse_min_run_time_active
          - service: number.set_value
            data:
              value: 0
            target:
              entity_id: 
